# Generated by Django 6.0.2 on 2026-02-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичная настройка'),
        ),
        migrations.AddField(
            model_name='settings',
            name='key',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Ключ'),
        ),
        migrations.AddField(
            model_name='settings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
